### ISSUE TITLE
3D model assets request

### ISSUE THREAD

**Issue by jbruns** [Rodmg/linamp#3]
Once you are happy with the printable or other physical assets of the embedded player build, I’d love to have a look at those in order to recreate, iterate and build on. Thanks for sharing this project, it is truly awesome!

**Comment by roninniagara** [comment]
+1 

I just got the screen and got it up and running today. GLORIOUS!!!!!!!

Now we just need a case :)

Much love to those who made this possible.

**Comment by Rodmg** [comment]
Thank you!, As a way for supporting this project, I'll be selling a digital package that will include all the production assets (including 3D models), guides on sourcing parts, orderinng custom parts, OS image, etc.

I'm currently working on the guides, I'll post here once it's available.

**Comment by jbruns** [comment]
EXCELLENT. Thanks, will definitely be glad to purchase the package.

**Comment by roninniagara** [comment]
I will only need the 3d print files at most - but will buy the package to support the project. I posted on twitter about it - and the response was pretty amazing. I think if this was advertised more/more word of mouth this could really take off!

Thanks for the heads up about the incoming package. I love supporting projects that are active and fun!

**Comment by Chankster** [comment]
Any update?  Would love to get the case made somewhere.

**Comment by Rodmg** [comment]
Hi!, I'm finishing the last details, will be publishing it this week

**Comment by roninniagara** [comment]
can't wait!

**Comment by Rodmg** [comment]
UPDATE: The Linamp DIY Digital Pack is now available! you can purchase it here: https://store.linamp.org

Thanks for your support!
